### ISSUE TITLE
Groupby notation is not working 

### ISSUE THREAD

**Issue by avangerus** [DevExpress/DevExtreme-PHP-Data#26] opened 2019-07-15 19:45 UTC
groupby in lazy load mode library loads only one group selector. Other seloctors is not working.

example:

server get: group: [{"selector":"ProductCategoryName","isExpanded":false},{"selector":"DateKey","groupInterval":"quarter","isExpanded":false}]

but data groups only by DateKey. ProductCategoryName is ignored.

Thank you in advance.

**Comment by NickMitrokhin** [comment] 2019-07-30 12:16
Hi,
This repository has an example in the [example](https://github.com/DevExpress/DevExtreme-PHP-Data/tree/master/example) folder. Would you please describe what steps I need to perform with the example to see the issue?

**Comment by NickMitrokhin** [comment] 2019-10-02 10:45
@avangerus, it seems that the issue is not reproducible anymore. So, I closing this issue. Feel free to post a comment if you have any issues.

**Closed by NickMitrokhin** 2019-10-02 10:45 UTC
